version: '3.9'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid
    restart: always
    ports:
      - "4444:4444"
    volumes:
      - ".:/etc/selenoid:ro" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-limit=10", "-mem=256m", "-cpu=1.0", "-session-delete-timeout=3s", "-timeout=7s"]


  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]


  web:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    restart: always
    links:
      - selenoid
    ports:
      - "5000:5000"

#  selenoid-chrome:
#    image: selenoid/chrome:latest
#    init: true
#  selenoid-firefox:
#    image: selenoid/firefox:latest
#    init: true
#  selenoid-edge:
#    image: browsers/edge
#    init: true
#  selenoid-safari15:
#    image: browsers/safari:15.0
#    init: true