name: publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the hello-docker Docker image
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login ghcr.io -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker build . --tag vgoroshenko/the-internet-demo:latest
          docker push vgoroshenko/the-internet-demo:latest